In [ ]:
# GETTING INFORMATION ABOUT THE BUSINESS OR THE ORGANIZATION
# KNOW THE PROBLEM AT HAND
# GETTING THE WRIGHT DATA
#EDA EXPLORATIVE DATA ANALYSIS
    # DATA CLEANING
    # DATA TRANSFORMATION
    # DECRIPTIVE ANALYIS(PYTHON, POWERBI, TABLEAU)
    # DATA VISUALIZATION(PYTHON, POWERBI, TABLEAU)
#MACHINE LEARNING(PYTHON,LINEAR REGRESSION,BINARY CLASSIFICATION,MULTICLASSIFICATION,CLUSTERING,TEXT OR SENTIMENT ANALYSIS)
    # PREPROCESSING
    # MODEL BUILDING
    # EVALUATION(VERIFICATION)
    # MODEL DEPLOYMENT
# DEEP LEARNING

In [2]:
# NUMPY : NUMERICAL PYTHON
import numpy as np


In [3]:
arr1 = np.array([75,85,60,47])
arr1 


array([75, 85, 60, 47])

In [6]:
arr1.ndim #checking the numbers of array dimension


1

In [10]:
arr1.shape 

(4,)

In [14]:
arr1.dtype


dtype('int32')

In [10]:
arr2 = np.array([[34, 56, 23, 66, 76], [65,77,65,34,21]])
arr2

array([[34, 56, 23, 66, 76],
       [65, 77, 65, 34, 21]])

In [11]:
arr2.shape

(2, 5)

In [12]:
arr2.ndim

2

In [22]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [30]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(60)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones((5,5))* 15

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [14]:
# lin shape, is use to generate evenly spaced over a spacified interval
np.linspace(20,90)

array([20.        , 21.42857143, 22.85714286, 24.28571429, 25.71428571,
       27.14285714, 28.57142857, 30.        , 31.42857143, 32.85714286,
       34.28571429, 35.71428571, 37.14285714, 38.57142857, 40.        ,
       41.42857143, 42.85714286, 44.28571429, 45.71428571, 47.14285714,
       48.57142857, 50.        , 51.42857143, 52.85714286, 54.28571429,
       55.71428571, 57.14285714, 58.57142857, 60.        , 61.42857143,
       62.85714286, 64.28571429, 65.71428571, 67.14285714, 68.57142857,
       70.        , 71.42857143, 72.85714286, 74.28571429, 75.71428571,
       77.14285714, 78.57142857, 80.        , 81.42857143, 82.85714286,
       84.28571429, 85.71428571, 87.14285714, 88.57142857, 90.        ])

In [40]:
 # the eye is to create 2 dm having 0 elsewhere and 1 diagonal
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
# arange  is use to arrange specific interval

arr4 = np.arange(1,101)
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [44]:
arr4 = np.arange(1,101,5)
arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [46]:
arr4 = np.arange(1,101,10)
arr4

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
arr5 = np.random.randint(15,105,10)
arr5

array([97, 77, 96, 73, 41, 17, 38, 55, 51, 59])

In [52]:
arr5 = np.random.randint(15,105,100)
arr5

array([ 82,  97,  44,  51,  45,  53,  26,  39,  74,  40,  70, 101,  61,
        37,  74,  93,  76,  61,  53,  83,  16, 102,  76,  40,  76,  64,
        57,  52,  57,  49,  46, 103,  31,  85,  46,  84,  50,  81,  85,
        52,  64,  31,  70,  64,  83,  43,  95, 104,  96,  69,  91,  43,
        24, 101,  86,  17,  85,  52,  86,  45,  40,  61,  95,  65,  32,
        63,  34,  47,  63, 102,  45,  80,  30,  17,  67,  53,  26,  84,
        45,  88,  72,  31,  57,  77,  17,  16,  71,  39, 103,  76,  33,
        97,  88,  27,  84,  94,  24,  25,  97,  69])

In [58]:
# seed
np.random.seed(5)
arr5 = np.random.randint(15,105,100)
arr5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [60]:
arr6 = arr5.reshape((10,10))
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73,  15,  95,  19,  51,  66,  42,  46],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [62]:
arr6[4,5]

33

In [64]:
arr6[3:7,3:6]

array([[15, 95, 19],
       [98, 34, 33],
       [18, 93, 42],
       [46, 24, 53]])

In [66]:
arr6[0:4,7:10]

array([[45, 95, 22],
       [90, 80, 62],
       [16, 97, 31],
       [66, 42, 46]])

In [68]:
# broadcasting is use to change the particular area selected to a givin figure
arr6[0:4,7:10] = 100
arr6

array([[ 93,  76,  31,  88,  23,  77,  42, 100, 100, 100],
       [ 91,  30,  68,  95,  42,  59,  92, 100, 100, 100],
       [ 45,  99, 101,  33,  24,  56,  77, 100, 100, 100],
       [ 93,  20,  73,  15,  95,  19,  51, 100, 100, 100],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [70]:
arr7 = arr6.flatten()
arr7

array([ 93,  76,  31,  88,  23,  77,  42, 100, 100, 100,  91,  30,  68,
        95,  42,  59,  92, 100, 100, 100,  45,  99, 101,  33,  24,  56,
        77, 100, 100, 100,  93,  20,  73,  15,  95,  19,  51, 100, 100,
       100,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [72]:
np.sum(arr7)

6189

In [74]:
np.max(arr7)

104

In [78]:
np.min(arr7)

15

In [80]:
np.mean(arr7)

61.89

In [84]:
np.median(arr2)

60.5

In [86]:
# percentile is the sum of pecertage
np.percentile(arr7,50)

59.5

In [88]:
# argmax is use to check the locationof the maximum number
np.argmax(arr7)

58

In [90]:
# argmin is use to check the location of the minimum number
np.argmin(arr7)

33

In [92]:
#domain knowledge
# communication skills
#problem-solving and critical thinking
#collaboration and teamwork
#ethics and data privacy
# project management
# business acumen
# adaptability and continuons learning
# the art of commuication
# tailoring communication
# persuasive communication
# mastering visualization tools
#choosing the right visuals
# design principles
# data storytelling and context
# 

In [95]:
import pandas as pd